### ISSUE TITLE
Use of "resetOnDismiss"

### ISSUE THREAD

**Issue by MarKco** [shaileshmamgain5/TwoStageRate#2]
I noticed the `resetOnDismiss(true)` flag works only if the ratingBar is dismissed. If - when prompted to enter a review - I click on "No thanks", I'm not prompted anymore even though I set the resetOnDismiss flag.

Is there a way to be prompted again after a number of events if I clicked on "No, thanks!" when prompted to post a review?

I tried the following:

`        rate.setOnDialogDismissedListener(new DialogDismissedListener() {
            @Override
            public void onDialogDismissed() {
                rate.settings.launchTimes = 0;
            }
        });
`

but it seems to me it's never triggered.

Thank you
Marco

**Comment by shaileshmamgain5** [comment]
resetOnDismiss(boolean b) will work only when user clicks on a region outside the dialog. To reset when user declines to rate on playstore or give feedback user below code (added in new version, make sure to update the dependency as well).

'twoStageRate.resetOnFeedBackDeclined(true).resetOnRatingDeclined(true);'

These are false by default. 

Thank you for reporting the issue . Cheers !!
