### ISSUE TITLE
My users see this dialog to often

### ISSUE THREAD

**Issue by csdevteam** [shaileshmamgain5/TwoStageRate#5]
Hello. I have these rules: 
TwoStageRate twoStageRate = TwoStageRate.with(this);
twoStageRate.setInstallDays(3);

BUT

Dialog will show after 5 runs of my app. Why? This is very urgent bug

Full code:

`TwoStageRate twoStageRate = TwoStageRate.with(this);

        twoStageRate.setInstallDays(rateAppNumberOfDaysBeforeShowDialog);

        //If user dismisses it, it simply resets again. (when user dismissed by clicking anywhere else on screen)
        twoStageRate.resetOnDismiss(true);  //it is true by default

        //If user gives rating the first time but declines to give playstore rating/ feedback we can reset the
        //TwoStageRate. These are false by default.
        twoStageRate.resetOnFeedBackDeclined(true).resetOnRatingDeclined(true);

        //You may choose to show/hide your app icon in rating prompt (default true)
        twoStageRate.setShowAppIcon(true);

        //Setting texts for initial prompt
        twoStageRate.setRatePromptTitle(RATE_INITIAL_TITLE).
                setRatePromptLaterText(RATE_LATER_TEXT).setRatePromptNeverText(RATE_NEVER_TEXT).setRatePromptDismissible(false);

        //Setting texts for confirmation dialog
        twoStageRate.setConfirmRateDialogTitle(RATE_CONFIRMATION_TITLE).
                setConfirmRateDialogDescription(RATE_CONFIRMATION_DESCRIPTION).
                setConfirmRateDialogPositiveText(RATE_POSITIVE_BUTTON_TEXT).
                setConfirmRateDialogNegativeText(RATE_NEGATIVE_BUTTON_TEXT).
                setConfirmRateDialogDismissible(true);

        //Setting texts for feedback title
        twoStageRate.setFeedbackDialogTitle(RATE_FEEDBACK_TITLE).
                setFeedbackDialogDescription(RATE_FEEDBACK_DIALOG_DESCRIPTION).
                setFeedbackDialogPositiveText(RATE_FEEDBACK_POSITIVE_BUTTON_TEXT).
                setFeedbackDialogNegativeText(RATE_NEGATIVE_BUTTON_TEXT).
                setFeedbackDialogDismissible(false);`

**Comment by shaileshmamgain5** [comment]
The library shows dialog whenever any of condition is met
1 ) Install days exceed set limit --> By default it is set to 5 days.
2) App launch time exceeds a limit --> By default it is 5 times.
3) Any event occurs exceeds limit --> By default it is 10 times.

So please set a launch time number to the app, if you want to make it irrelevant for the decision of showing dialog, please enter it to me any large number. like

twoStageRate.setInstallDays(3).setLaunchTimes(Integer.MAX_VALUE).setEventsTimes(Integer.MAX_VALUE);

**Comment by csdevteam** [comment]
Thank you
